### ISSUE TITLE
[a régler] Certaines touches ne fonctionnent pas

### ISSUE THREAD

**Issue by SimpleSoftwares** [SimpleSoftwares/Blueflap#1]
Sur la page Google.com par exemple, il est impossible de taper certaines lettres dans le champ de recherche et de valider avec ENTER

**Comment by Bat41** [comment]
C'est corriger avec la 1.7.5 d'Awesomium ! Il reste juste la touche Entrée qui valide pas le formulaire, mais c'est moins grave et ça viendra surement !

**Comment by SimpleSoftwares** [comment]
Dans ce cas je ferme :smile:
